security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/ms-user/login
            provider: app_user_provider
            stateless: true
            anonymous: true
            json_login:
                check_path: /ms-user/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        user_create:
            pattern: ^/ms-user/users
            methods: POST,
            anonymous: true

        api:
            pattern: ^/ms-user
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/ms-user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ms-user/users, methods:[POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ms-user, roles: IS_AUTHENTICATED_FULLY }